---
# Label: ansible_project_zookeeper_image_stream
# Title: create the Ansible template for the Apache Zookeeper image stream in OpenShift
# Mission: create the Ansible template for the Apache Zookeeper image stream in OpenShift
# Milestone: Automate Cluster Manager Deployment
# Column: Automate Cluster Manager Deployment

apiVersion: image.openshift.io/v1
kind: ImageStream
spec:
  tags:
  - from:
      kind: DockerImage
      name: zookeeper
    name: 3.6.2
