spec:
  template:
    spec:
      containers:
        - name: vertx
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_OPTIONS
              value: '-Dvertx.cacheDirBase=/tmp -Dvertx.jgroups.config=default'
            - name: langueNom
              value: frFR
              
            - name: zookeeperNomHote
              value: computate-zookeeper.computateorg.svc
              
            - name: zookeeperPort
              value: 8080
              
            - name: appliChemin_enUS
              value: /usr/local/src/computate.org
              
            - name: nomDomaine
              value: computate.org
              
            - name: nomEnsembleDomaine
              value: org.computate.site
              
            - name: autresLangues
              value: enUS
              
            - name: suffixeSrcMainJava
              value: /src/main/java
              
            - name: suffixeSrcGenJava
              value: /src/gen/java
              
            - name: cheminsRelatifsARegarder
              value: src/main/java/org/computate/site/frFR
              
            - name: nomEntreprise
              value: computate.org
              
            - name: siteCrypte
              value: true
              
            - name: jdbcUrl
              value: "jdbc:postgresql://pgsql.computateorg.svc:5432/site"
              
            - name: jdbcUtilisateur
              value: computate
              
            - name: jdbcMotDePasse
              value: "es54IPtGnSy0T5o1"
              
            - name: siteNomHote
              value: www.computate.org
              
            - name: siteUrlBase
              value: https://www.computate.org
              
            - name: authRoyaume
              value: computate.org
              
            - name: authRessource
              value: computate.org
              
            - name: authSecret
              value: eca1c897-f054-4eef-99a3-66de89f8aed0
              
            - name: authUrl
              value: https://auth.computate.org/auth
              
            - name: authSslRequis
              value: all
              
            - name: sslJksChemin
              value: /srv/heytate.com/server.jks
              
            - name: sslJksMotDePasse
              value: "T@wgf77q~
              value: 3t^KtY"
              
            - name: selCryptage
              value: asoi352tgbnrj64
              
            - name: sitePort
              value: 8080
              
            - name: motDePasseCryptage
              value: bobno3i4867fh3sqq
              
            - name: solrUrl
              value: http://openshift-solr.computateorg.svc:8983/solr/new_core
              
            - name: solrUrlComputate
              value: http://localhost:10383/solr/computate
              
            - name: apiContactMail
              value: ctate@redhat.com
              
            - name: vertxServiceAddresse
              value: api