apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: keycloak-prod
  namespace: keycloak
spec:
  acme:
    email: computate@computate.org
    preferredChain: ''
    privateKeySecretRef:
      name: keycloak-prod
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            name: keycloak-ingress
