---

SITE_NAME: computateorg
SITE_DISPLAY_NAME: your website
SITE_PUBLIC_URL: https://www.computate.org
MAILING_LIST_URL: https://computate.topicbox.com/groups/computate
SITE_HOST_NAME: localhost
SITE_PORT: 10180
SITE_BASE_URL: "http://localhost:10180"
SITE_ZONE: America/Denver
SITE_LOCALE: en-US
SITE_INSTANCES: 5
WORKER_POOL_SIZE: 2
VERTX_MAX_EVENT_LOOP_EXECUTE_TIME: 30
VERTX_WARNING_EXCEPTION_SECONDS: 60
CLUSTER_HOST_NAME: localhost
CLUSTER_PORT: 10181
GITHUB_ORG: "computate-org"
QUAYIO_ORG: "computateorg"
SITE_POWERED_BY_URL: "https://access.redhat.com/products/openshift-online-red-hat"
SITE_POWERED_BY_NAME: "OpenShift Online"
SITE_POWERED_BY_IMAGE_URI: "/svg/openshift.svg"

STATIC_BASE_URL: "http://localhost:10180/static"
STATIC_PATH: "/usr/local/src/computateorg-static"

API_CONTACT_EMAIL: 
API_COUNTER_RESUME: 0
API_COUNTER_FETCH: 10

JDBC_HOST: localhost
JDBC_PORT: 5432
JDBC_DATABASE: computateorg
JDBC_USERNAME: computateorg
JDBC_PASSWORD: 
JDBC_MAX_POOL_SIZE: 10
JDBC_MAX_WAIT_QUEUE_SIZE: 1000

AUTH_REALM: 
AUTH_RESOURCE: 
AUTH_SECRET: 
AUTH_HOST_NAME: 
AUTH_PORT: 443
AUTH_SSL: true
AUTH_SSL_REQUIRED: all
AUTH_TOKEN_URI: /auth/realms/AUTH_REALM/protocol/openid-connect/token

ZOOKEEPER_HOST_NAME: localhost
ZOOKEEPER_PORT: 2181
ZOOKEEPER_BASE_SLEEP_TIME_MILLIS: 5000
ZOOKEEPER_MAX_SLEEP_MILLIS: 5000
ZOOKEEPER_MAX_RETRIES: 5
ZOOKEEPER_CONNECTION_TIMEOUT_MILLIS: 3000
ZOOKEEPER_SESSION_TIMEOUT_MILLIS: 5000

SOLR_URL: http://localhost:8983/solr/computateorg
SOLR_HOST_NAME: localhost
SOLR_PORT: 8983
SOLR_COLLECTION: computateorg
SOLR_COLLECTION_COMPUTATE: computate
SOLR_WORKER_COMMIT_WITHIN_MILLIS: 10000

EMAIL_HOST: 
EMAIL_PORT: 
EMAIL_SSL: 
EMAIL_AUTH: 
EMAIL_USERNAME: 
EMAIL_PASSWORD: 
EMAIL_FROM: 
EMAIL_ADMIN: 

REFRESH_DATA_PAUSE_IN_SECONDS: 10
ENABLE_REFRESH_DATA: false
ENABLE_REFRESH_DATA_Article: true
ENABLE_REFRESH_DATA_Course: true
ENABLE_REFRESH_DATA_SitePage: true
ENABLE_REFRESH_DATA_SiteHtm: true
ENABLE_REFRESH_DATA_PixelArt: true

ENABLE_IMPORT_DATA: true
ENABLE_IMPORT_DATA_Article: true
ENABLE_IMPORT_DATA_Course: true
ENABLE_IMPORT_DATA_SitePage: true
ENABLE_IMPORT_DATA_SiteHtm: true
ENABLE_IMPORT_DATA_PixelArt: true

# The Auth roles required to be an admin in the site. 
AUTH_ROLES_ADMIN: ['SiteAdmin']
# The Auth roles required to add and modify site user records. 
AUTH_ROLES_REQUIRED_SiteUser: ['SiteAdmin']
# The Auth roles required to add and modify article records. 
AUTH_ROLES_REQUIRED_Article: ['SiteAdmin']
# The Auth roles required to add and modify course records. 
AUTH_ROLES_REQUIRED_Course: ['SiteAdmin']
# The Auth roles required to add and modify article records. 
AUTH_ROLES_REQUIRED_SitePage: ['SiteAdmin']
# The Auth roles required to add and modify HTML records. 
AUTH_ROLES_REQUIRED_SiteHtm: ['SiteAdmin']
# The Auth roles required to add and modify pixel art records. 
AUTH_ROLES_REQUIRED_PixelArt: ['SiteAdmin']
