---

SITE_NAME: computate.org
SITE_DISPLAY_NAME: computate.org
SITE_HOST_NAME: localhost
SITE_PORT: 10180
SITE_BASE_URL: "http://localhost:10180"
SITE_ZONE: America/Denver
SITE_LOCALE: en-US
SITE_INSTANCES: 5
WORKER_POOL_SIZE: 2
VERTX_WARNING_EXCEPTION_SECONDS: 10
CLUSTER_HOST_NAME: localhost
CLUSTER_PORT: 10181
GITHUB_ORG: "computate-org"
QUAYIO_ORG: "computate"
PROJECT_POWERED_BY_URL: "https://access.redhat.com/products/openshift-online-red-hat"
PROJECT_POWERED_BY_NAME: "OpenShift Online"
PROJECT_POWERED_BY_IMAGE_URI: "/svg/openshift.svg"

STATIC_BASE_URL: "http://localhost:10180/static"
STATIC_PATH: "/usr/local/src/computate.org-static"

API_CONTACT_EMAIL: 
API_COUNTER_PAUSE: 10
API_COUNTER_RESUME: 5
API_COUNTER_FETCH: 10

JDBC_HOST: localhost
JDBC_PORT: 5432
JDBC_DATABASE: computate.org
JDBC_USERNAME: computate.org
JDBC_PASSWORD: 
JDBC_MAX_POOL_SIZE: 10
JDBC_MAX_WAIT_QUEUE_SIZE: 1000

AUTH_REALM: 
AUTH_RESOURCE: 
AUTH_SECRET: 
AUTH_HOST_NAME: 
AUTH_PORT: 443
AUTH_SSL: true
AUTH_SSL_REQUIRED: all
AUTH_TOKEN_URI: /auth/realms/AUTH_REALM/protocol/openid-connect/token

ZOOKEEPER_HOST_NAME: localhost
ZOOKEEPER_PORT: 2181

SOLR_URL: http://localhost:8983/solr/computate.org
SOLR_HOST_NAME: localhost
SOLR_PORT: 8983
SOLR_COLLECTION: computate.org
SOLR_COLLECTION_COMPUTATE: computate
SOLR_WORKER_COMMIT_WITHIN_MILLIS: 10000

EMAIL_HOST: 
EMAIL_PORT: 
EMAIL_SSL: 
EMAIL_AUTH: 
EMAIL_USERNAME: 
EMAIL_PASSWORD: 
EMAIL_FROM: 
EMAIL_ADMIN: 

REFRESH_DATA_PAUSE_IN_SECONDS: 10
ENABLE_REFRESH_DATA: false
ENABLE_REFRESH_DATA_SitePage: true
ENABLE_REFRESH_DATA_SiteHtm: true
ENABLE_REFRESH_DATA_Article: true

ENABLE_IMPORT_DATA: true
ENABLE_IMPORT_DATA_SitePage: true
ENABLE_IMPORT_DATA_SiteHtm: true
ENABLE_IMPORT_DATA_Article: true

# The Auth roles required to be an admin in the site. 
AUTH_ROLES_ADMIN: ['SiteAdmin']
# The Auth roles required to add and modify site user records. 
AUTH_ROLES_REQUIRED_SiteUser: ['SiteAdmin']
# The Auth roles required to add and modify article records. 
AUTH_ROLES_REQUIRED_SitePage: ['SiteAdmin']
# The Auth roles required to add and modify HTML records. 
AUTH_ROLES_REQUIRED_SiteHtm: ['SiteAdmin']
# The Auth roles required to add and modify article records. 
AUTH_ROLES_REQUIRED_Article: ['SiteAdmin']
