---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: "2022-07-05T14:12:58Z"
  generation: 34
  name: computateorg
  namespace: computateorg
  resourceVersion: "2354860960"
  selfLink: /apis/apps.openshift.io/v1/namespaces/computateorg/deploymentconfigs/computateorg
  uid: 928f7dce-fc6c-11ec-8c86-123713f594ec
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: computateorg
    deploymentconfig: computateorg
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: computateorg
        deploymentconfig: computateorg
    spec:
      containers:
      - env:
        - name: AUTH_REALM
          valueFrom:
            secretKeyRef:
              key: AUTH_REALM
              name: computateorg-secret
        - name: AUTH_RESOURCE
          valueFrom:
            secretKeyRef:
              key: AUTH_RESOURCE
              name: computateorg-secret
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              key: AUTH_SECRET
              name: computateorg-secret
        - name: AUTH_HOST_NAME
          valueFrom:
            secretKeyRef:
              key: AUTH_HOST_NAME
              name: computateorg-secret
        - name: AUTH_PORT
          valueFrom:
            secretKeyRef:
              key: AUTH_PORT
              name: computateorg-secret
        - name: AUTH_SSL
          valueFrom:
            secretKeyRef:
              key: AUTH_SSL
              name: computateorg-secret
        - name: AUTH_URL
          valueFrom:
            secretKeyRef:
              key: AUTH_URL
              name: computateorg-secret
        - name: AUTH_TOKEN_URI
          value: /auth/realms/COMPUTATE.ORG/protocol/openid-connect/token
        - name: EMAIL_AUTH
          valueFrom:
            secretKeyRef:
              key: EMAIL_AUTH
              name: computateorg-secret
        - name: EMAIL_FROM
          valueFrom:
            secretKeyRef:
              key: EMAIL_FROM
              name: computateorg-secret
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              key: EMAIL_HOST
              name: computateorg-secret
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: EMAIL_PASSWORD
              name: computateorg-secret
        - name: EMAIL_PORT
          valueFrom:
            secretKeyRef:
              key: EMAIL_PORT
              name: computateorg-secret
        - name: EMAIL_SSL
          valueFrom:
            secretKeyRef:
              key: EMAIL_SSL
              name: computateorg-secret
        - name: EMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              key: EMAIL_USERNAME
              name: computateorg-secret
        - name: JDBC_HOST
          valueFrom:
            secretKeyRef:
              key: JDBC_HOST
              name: computateorg-secret
        - name: JDBC_PORT
          valueFrom:
            secretKeyRef:
              key: JDBC_PORT
              name: computateorg-secret
        - name: JDBC_DATABASE
          valueFrom:
            secretKeyRef:
              key: JDBC_DATABASE
              name: computateorg-secret
        - name: JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              key: JDBC_USERNAME
              name: computateorg-secret
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: JDBC_PASSWORD
              name: computateorg-secret
        - name: OPENSHIFT_SERVICE
          value: computateorg
        - name: CLUSTER_PORT
          value: "8081"
        - name: ZOOKEEPER_HOST_NAME
          value: zookeeper.computateorg.svc
        - name: ZOOKEEPER_PORT
          value: "2181"
        - name: SOLR_HOST_NAME
          value: solr.computateorg.svc
        - name: SOLR_PORT
          value: "8983"
        - name: SOLR_URL
          value: http://solr.computateorg.svc:8983/solr/computateorg
        - name: SOLR_COLLECTION
          value: computateorg
        - name: SITE_HOST_NAME
          value: www.computate.org
        - name: SITE_PORT
          value: "8080"
        - name: SITE_BASE_URL
          value: https://www.computate.org
        - name: STATIC_BASE_URL
          value: https://computate.neocities.org
        - name: STATIC_PATH
        - name: SITE_ZONE
          value: America/Denver
        - name: SITE_LOCALE
          value: en-US
        - name: JAVA_MAIN_CLASS
          value: org.computate.site.enus.vertx.MainVerticle
        - name: SITE_INSTANCES
          value: "5"
        - name: WORKER_POOL_SIZE
          value: "5"
        - name: DYNAMIC_PAGE_PATH
          value: /root/src/computateorg/src/main/resources/page
        - name: VERTX_WARNING_EXCEPTION_SECONDS
          value: "60"
        - name: CLUSTER_HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CLUSTER_PUBLIC_HOST_NAME
          value: computateorg.computateorg.svc
        - name: API_COUNTER_FETCH
          value: "10"
        - name: API_COUNTER_RESUME
          value: "5"
        - name: ENABLE_IMPORT_DATA
          value: "True"
        - name: ENABLE_IMPORT_DATA_Article
          value: "true"
        - name: ENABLE_IMPORT_DATA_SitePage
          value: "true"
        - name: ENABLE_IMPORT_DATA_SiteHtm
          value: "true"
        - name: ENABLE_REFRESH_DATA
          value: "True"
        - name: AUTH_ROLES_ADMIN
          value: '["SiteAdmin"]'
        - name: AUTH_ROLES_REQUIRED_SiteUser
          value: '["SiteAdmin"]'
        - name: AUTH_ROLES_REQUIRED_Article
          value: '["SiteAdmin"]'
        - name: AUTH_ROLES_REQUIRED_SitePage
          value: '["SiteAdmin"]'
        - name: AUTH_ROLES_REQUIRED_SiteHtm
          value: '["SiteAdmin"]'
        - name: FONTAWESOME_KIT
          value: https://kit.fontawesome.com/59d19567d5.js
        - name: COMPUTATE_SRC
          value: /root/src/computate
        - name: COMPUTATE_SEARCH_SRC
          value: /root/src/computate-search
        - name: COMPUTATE_VERTX_SRC
          value: /root/src/computate-vertx
        - name: DYNAMIC_PAGE_PATHS
          value: '["/root/src/computate-search/page","/root/src/computateorg/page"]'
        - name: SITE_SRC
          value: /root/src/computateorg
        - name: I18N_PATHS
          value: '["/root/src/computate/src/main/resources/org/computate/i18n/i18n_enUS.yml"]'
        image: quay.io/computateorg/computateorg@sha256:358c8d1264f6841e5e7a7ea899f55b97b86d4d369e731c85df3cafd332a61c33
        imagePullPolicy: Always
        name: computateorg
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: cluster
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 3333
          name: jms
          protocol: TCP
        - containerPort: 8998
          name: debug
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        workingDir: /root/src
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - computateorg
      from:
        kind: ImageStreamTag
        name: computateorg:latest
        namespace: computateorg
      lastTriggeredImage: quay.io/computateorg/computateorg@sha256:358c8d1264f6841e5e7a7ea899f55b97b86d4d369e731c85df3cafd332a61c33
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-11-08T13:32:28Z"
    lastUpdateTime: "2022-11-08T13:33:03Z"
    message: replication controller "computateorg-29" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-07-12T00:53:58Z"
    lastUpdateTime: "2023-07-12T00:53:58Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 29
  observedGeneration: 34
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-branch: master
    fabric8.io/git-commit: ef578712f23dbc2da456eee41ffc8036a209d263
    fabric8.io/iconUrl: img/icons/vertx.svg
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  creationTimestamp: "2019-04-12T21:59:11Z"
  labels:
    app: computate.org
    expose: "true"
    provider: fabric8
    version: 1.0.0-SNAPSHOT
  name: computateorg
  namespace: computateorg
  resourceVersion: "2010473071"
  selfLink: /api/v1/namespaces/computateorg/services/computateorg
  uid: 34551720-5d6e-11e9-84bb-12b5519f9b58
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: cluster
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: computateorg
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
