apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  namespace: keycloak
  name: computate
  labels:
    app: sso
    realm: COMPUTATE
spec:
  keycloakCRName: sso
  realm:
    id: "COMPUTATE"
    realm: "COMPUTATE"
    enabled: true
    displayName: "COMPUTATE"
    registrationAllowed: true
    resetPasswordAllowed: true
    editUsernameAllowed: true
    rememberMe: true
    verifyEmail: true
    loginWithEmailAllowed: true
    identityProviders:
      - displayName: GitHub
        enabled: true
        alias: github
        providerId: github
        updateProfileFirstLoginMode: "on"
        trustEmail: false
        storeToken: false
        addReadTokenRoleOnCreate: false
        authenticateByDefault: false
        linkOnly: false
        firstBrokerLoginFlowAlias: "first broker login"
        config:
          "syncMode": "IMPORT"
          "useJwksUrl": "true"

    groups:
      - id: User
        name: User
      - id: SiteAdmin
        name: SiteAdmin
        subGroups:
          - id: User
      - id: SuperAdmin
        name: SuperAdmin
        subGroups:
          - id: SiteAdmin
    users:
      - id: computate
        username: computate
        groups:
          - SuperAdmin
    clientScopes:
      - id: computate
        name: computate
        description: A client scope for the computate client
        protocol: openid-connect
        protocolMappers:
          - config:
              access.token.claim: 'true'
              id.token.claim: 'false'
              included.client.audience: 'computate'
            consentRequired: false
            id: computate
            name: computate
            protocol: openid-connect
            protocolMapper: oidc-audience-mapper
      - id: computate-profile
        name: profile
        description: "OpenID Connect built-in scope: profile"
        protocol: openid-connect
        protocolMappers:
          - config:
              access.token.claim: 'true'
              claim.name: email_verified
              id.token.claim: 'true'
              jsonType.label: boolean
              user.attribute: emailVerified
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-email-verified
            name: email verified
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: preferred_username
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: username
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-username
            name: username
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: groups
              id.token.claim: 'true'
              jsonType.label: String
              multivalued: 'true'
              user.attribute: foo
            consentRequired: false
            id: computate-groups
            name: groups
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
          - config:
              access.token.claim: 'true'
              claim.name: family_name
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: lastName
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-family-name
            name: family name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: given_name
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: firstName
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-given-name
            name: given name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: email
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: email
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-email
            name: email
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: middle_name
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: middleName
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-middle-name
            name: middle name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: locale
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: locale
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-locale
            name: locale
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: nickname
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: nickname
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-nickname
            name: nickname
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: updated_at
              id.token.claim: 'true'
              jsonType.label: long
              user.attribute: updatedAt
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-updated-at
            name: updated at
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              id.token.claim: 'true'
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-full-name
            name: full name
            protocol: openid-connect
            protocolMapper: oidc-full-name-mapper
          - config:
              access.token.claim: 'true'
              claim.name: profile
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: profile
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-profile
            name: profile
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: resource_access.${client_id}.roles
              jsonType.label: String
              multivalued: 'true'
              user.attribute: foo
            consentRequired: false
            id: computate-client-roles
            name: client roles
            protocol: openid-connect
            protocolMapper: oidc-usermodel-client-role-mapper
          - config:
              access.token.claim: 'true'
              claim.name: zoneinfo
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: zoneinfo
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate-zoneinfo
            name: zoneinfo
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: realm_access.roles
              jsonType.label: String
              multivalued: 'true'
              user.attribute: foo
            consentRequired: false
            id: computate-realm-roles
            name: realm roles
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
    defaultDefaultClientScopes:
      - computate
    clients:
      - id: computate
        clientId: computate
        standardFlowEnabled: true
        serviceAccountsEnabled: true
        authorizationServicesEnabled: true
        frontchannelLogout: true
        protocol: openid-connect
        redirectUris:
          - http://localhost:12080/logout
          - http://localhost:12080/callback
        defaultClientScopes:
          - profile
          - computate
        authorizationSettings:
          decisionStrategy: AFFIRMATIVE

  instanceSelector:
    matchLabels:
      app: sso
