apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rerc
  namespace: rerc
spec:
  host: rerc.apps-crc.testing
  port:
    targetPort: http
  to:
    kind: Service
    name: rerc-web
    weight: 100
  wildcardPolicy: None
