---
# Label: project_backup_defaults
# Title: create some Ansible default variables for backing up all opendatapolicing data
# Mission: create some Ansible default variables for backing up all opendatapolicing data
# Milestone: Data Backup/Restore
# Column: Data Backup/Restore

target: project_backup
