apiVersion: smartvillage.computate.org/v1
kind: EdgePostgres
metadata:
  name: postgres
  namespace: postgres
spec:
  managementState: Managed
  postgres:
    enable_dev_nodeports: true
    instances:
      - name: postgres
        replicas: 1
        storage: 1Gi
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
          requests:
            memory: 200Mi
            cpu: 200m
    users:
      - name: smartvillage
        options: "SUPERUSER"
        databases:
          - smartvillage
      - name: scorpiobroker
        options: "SUPERUSER CREATEDB"
        databases:
          - scorpiobroker
      - name: rerc
        options: "SUPERUSER"
        databases:
          - rerc
      - name: opendatapolicing
        options: "SUPERUSER"
        databases:
          - opendatapolicing
    pg_hba:

      - "host smartvillage smartvillage all md5"
      - "local smartvillage smartvillage trust"

      - "host all scorpiobroker all md5"
      - "local all scorpiobroker trust"

      - "host all rerc all md5"
      - "local all rerc trust"

      - "host all opendatapolicing all md5"
      - "local all opendatapolicing trust"
