apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  additionalOptions:
    - name: proxy
      value: edge
  db:
    database: keycloak
    host: postgres-cluster-ha.postgres.svc.cluster.local
    port: 5432
    passwordSecret:
      name: keycloak-db-secret
      key: POSTGRES_PASSWORD
    usernameSecret:
      name: keycloak-db-secret
      key: POSTGRES_USERNAME
  hostname:
    hostname: keycloak.computate.org
  http:
    httpEnabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.global-static-ip-name: keycloak
      kubernetes.io/ingress.class: gce
      networking.gke.io/managed-certificates: keycloak
      networking.gke.io/v1beta1.FrontendConfig: keycloak
    className: gce
    