apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  externalAccess:
    enabled: true
  externalDatabase:
    enabled: true
  hostname:
    hostname: keycloak.computate.org
  http:
    httpEnabled: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      networking.gke.io/managed-certificates: networking-managed-cert
      networking.gke.io/v1beta1.FrontendConfig: networking-fc
      kubernetes.io/ingress.global-static-ip-name: computate
      kubernetes.io/ingress.class: gce
    className: gce
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: keycloak-db-secret
              key: POSTGRES_EXTERNAL_ADDRESS
        - name: KEYCLOAK_POSTGRESQL_SERVICE_HOST
          valueFrom:
            secretKeyRef:
              name: keycloak-db-secret
              key: POSTGRES_EXTERNAL_ADDRESS
    