---
# Label: ansible_project_keystore
# Title: create the Ansible template for the project keystore secret in OpenShift
# Mission: create the Ansible template for the project keystore secret in OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

apiVersion: v1
kind: Secret
type: Opaque
stringData:
  solr.in.sh: |-
    SOLR_SSL_ENABLED=true
    SOLR_SSL_KEY_STORE={{ SOLR_OPT }}/keystore/{{ SSL_JKS_FILENAME }}
    SOLR_SSL_KEY_STORE_PASSWORD={{ SSL_JKS_PASSWORD }}
    SOLR_SSL_TRUST_STORE={{ SOLR_OPT }}/keystore/{{ SSL_JKS_FILENAME }}
    SOLR_SSL_TRUST_STORE_PASSWORD={{ SSL_JKS_PASSWORD }}
    SOLR_SSL_NEED_CLIENT_AUTH=false
    SOLR_SSL_WANT_CLIENT_AUTH=false
    SOLR_SSL_KEY_STORE_TYPE=JKS
    SOLR_SSL_TRUST_STORE_TYPE=JKS
