apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: keycloak
    app.kubernetes.io/instance: sso
    app.kubernetes.io/managed-by: keycloak-operator
  name: sso
  namespace: sso
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keycloak
      app.kubernetes.io/instance: sso
      app.kubernetes.io/managed-by: keycloak-operator
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keycloak
        app.kubernetes.io/instance: sso
        app.kubernetes.io/managed-by: keycloak-operator
    spec:
      containers:
      - name: keycloak
        args:
          - start
          - --auto-build
          - --db=postgres
        env:
        - name: KC_HOSTNAME
          value: sso.computate.org
        - name: KC_HTTP_ENABLED
          value: "false"
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_HTTPS_PORT
          value: "8443"
        - name: KC_DB
          value: postgres
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-cluster-pguser-sso
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-cluster-pguser-sso
        - name: KC_DB_URL_DATABASE
          valueFrom:
            secretKeyRef:
              key: dbname
              name: postgres-cluster-pguser-sso
        - name: KC_DB_URL_HOST
          value: postgres.postgres.svc
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_CACHE
          value: ispn
        - name: KC_CACHE_STACK
          value: kubernetes
        - name: KC_PROXY
          value: edge
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              key: username
              name: sso-initial-admin
              optional: false
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: sso-initial-admin
              optional: false
        - name: jgroups.dns.query
          value: sso-discovery.sso
        image: quay.io/keycloak/keycloak:18.0.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 150
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 250
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
