apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    statefulset: postgres
  name: postgres
  namespace: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: postgres
    statefulset: postgres
