apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: solr
  namespace: solr
spec:
  replicas: 1
  busyBoxImage:
    repository: docker.io/library/busybox
    tag: 1.36.0-glibc
  solrImage:
    repository: docker.io/library/solr
    tag: 9.1.1
  dataStorage:
    persistent:
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi
  customSolrKubeOptions:
    podOptions:
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 8983
        fsGroup: 8983
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: solr
      resources:
        limits:
          memory: '2Gi'
          cpu: '1'
        requests:
          memory: '500Mi'
          cpu: '500m'
      volumes:
        - name: computate-configset
          source:
            configMap:
              defaultMode: 440
              name: computate-configset
          defaultContainerMount:
              mountPath: /opt/solr/server/solr/configsets/computate/conf
              name: computate-configset
  zookeeperRef:
    provided:
      replicas: 1
      persistence:
        spec:
          resources:
            requests:
              storage: 1Gi
      zookeeperPodPolicy:
        resources:
          limits:
            memory: '500Mi'
            cpu: '500m'
          requests:
            memory: '200Mi'
            cpu: '200m'
