apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: solr
  namespace: solr
spec:
  replicas: 1
  dataStorage:
    persistent:
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
  solrAddressability:
    commonServicePort: 8983
    external:
      domainName: apps-crc.testing
      ingressTLSTermination:
        tlsSecret: solr-certificate
      method: Ingress
      nodePortOverride: 8983
      useExternalAddress: false
    podPort: 8983
  customSolrKubeOptions:
    podOptions:
      openshift: true
      serviceAccountName: solr
      defaultInitContainerResources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
      resources:
        limits:
          cpu: '2'
          memory: 6Gi
        requests:
          cpu: '1'
          memory: 6Gi
      volumes:
        - defaultContainerMount:
            mountPath: /opt/solr/server/solr/configsets
            name: configsets
          name: configsets
          source:
            persistentVolumeClaim:
              claimName: solr-configsets
  zookeeperRef:
    provided:
      replicas: 1
      persistence:
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            limits:
              storage: 10Gi
            requests:
              storage: 10Gi
      zookeeperPodPolicy:
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
