apiVersion: smartvillage.computate.org/v1
kind: EdgeSolr
metadata:
  name: solr
  namespace: solr
spec:
  enable_dev_nodeports: true
  solr:
    name: solr
    route:
      create: true
      host_name: solr-solr.apps.crc.testing
    replicas: 1
    resources:
      limits:
        memory: 2Gi
        cpu: '2'
      requests:
        memory: 1Gi
        cpu: '1'
    configsets:
      - name: computate
        configmap: computate-configset
      - name: trailblazehunt
        configmap: trailblazehunt-configset
    collections:
      - name: computate
        configset: computate
      - name: smartvillage
        configset: computate
      - name: rerc
        configset: computate
      - name: opendatapolicing
        configset: computate
      - name: trailblazehunt
        configset: trailblazehunt
  zookeeper:
    host: zookeeper.zookeeper.svc
    port: 2181
