apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: computate-org
  namespace: keycloak
  labels:
    app: keycloak
    realm: COMPUTATE.ORG
spec:
  keycloakCRName: keycloak
  realm:
    id: "COMPUTATE.ORG"
    realm: "COMPUTATE.ORG"
    enabled: true
    displayName: "COMPUTATE.ORG"
    registrationAllowed: true
    resetPasswordAllowed: true
    editUsernameAllowed: true
    rememberMe: true
    verifyEmail: true
    loginWithEmailAllowed: true
    roles:
      realm:
        - id: SiteAdmin
          name: Site Admin
        - id: SuperAdmin
          name: Super Admin
#          composite: true
#          composites:
#            realm:
#              - SiteAdmin
    clientScopes:
      - id: computate.org
        name: computate.org
        description: A client scope for computate.org
        protocol: openid-connect
        protocolMappers: 
          - config:
              access.token.claim: 'true'
              id.token.claim: 'false'
              included.client.audience: 'computate.org'
            consentRequired: false
            id: computate-org
            name: computate.org
            protocol: openid-connect
            protocolMapper: oidc-audience-mapper
      - id: computate.org-profile
        name: profile
        description: "OpenID Connect built-in scope: profile"
        protocol: openid-connect
        protocolMappers: 
          - config:
              access.token.claim: 'true'
              claim.name: email_verified
              id.token.claim: 'true'
              jsonType.label: boolean
              user.attribute: emailVerified
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-email-verified
            name: email verified
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: preferred_username
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: username
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-username
            name: username
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: groups
              id.token.claim: 'true'
              jsonType.label: String
              multivalued: 'true'
              user.attribute: foo
            consentRequired: false
            id: computate.org-groups
            name: groups
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
          - config:
              access.token.claim: 'true'
              claim.name: family_name
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: lastName
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-family-name
            name: family name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: given_name
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: firstName
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-given-name
            name: given name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: email
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: email
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-email
            name: email
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: middle_name
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: middleName
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-middle-name
            name: middle name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: locale
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: locale
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-locale
            name: locale
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: nickname
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: nickname
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-nickname
            name: nickname
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: updated_at
              id.token.claim: 'true'
              jsonType.label: long
              user.attribute: updatedAt
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-updated-at
            name: updated at
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              id.token.claim: 'true'
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-full-name
            name: full name
            protocol: openid-connect
            protocolMapper: oidc-full-name-mapper
          - config:
              access.token.claim: 'true'
              claim.name: profile
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: profile
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-profile
            name: profile
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: resource_access.${client_id}.roles
              jsonType.label: String
              multivalued: 'true'
              user.attribute: foo
            consentRequired: false
            id: computate.org-client-roles
            name: client roles
            protocol: openid-connect
            protocolMapper: oidc-usermodel-client-role-mapper
          - config:
              access.token.claim: 'true'
              claim.name: zoneinfo
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: zoneinfo
              userinfo.token.claim: 'true'
            consentRequired: false
            id: computate.org-zoneinfo
            name: zoneinfo
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
          - config:
              access.token.claim: 'true'
              claim.name: realm_access.roles
              jsonType.label: String
              multivalued: 'true'
              user.attribute: foo
            consentRequired: false
            id: computate.org-realm-roles
            name: realm roles
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
    defaultDefaultClientScopes:
      - computate.org
    clients:
      - id: computate.org
        clientId: computate.org
        standardFlowEnabled: true
        serviceAccountsEnabled: true
        authorizationServicesEnabled: true
        frontchannelLogout: true
        protocol: openid-connect
        redirectUris:
          - http://localhost:12080/logout
          - http://localhost:12080/callback
          - https://oauth-openshift.apps-crc.testing/oauth2callback/sso
        defaultClientScopes:
          - profile
          - computate.org
        authorizationSettings:
          scopes:
            - id: POST
              name: POST
              displayName: POST
            - id: DELETE
              name: DELETE
              displayName: DELETE
            - id: GET
              name: GET
              displayName: GET
            - id: PATCH
              name: PATCH
              displayName: PATCH
            - id: PUTImport
              name: PUTImport
              displayName: PUTImport
            - id: Search
              name: Search
              displayName: Search
          resources:
            - name: SiteUser
              displayName: SiteUser
              uris:
                - /api/user
                - /user
              scopes:
                - id: POST
                  name: POST
                  displayName: POST
                - id: DELETE
                  name: DELETE
                  displayName: DELETE
                - id: GET
                  name: GET
                  displayName: GET
                - id: PATCH
                  name: PATCH
                  displayName: PATCH
                - id: PUTImport
                  name: PUTImport
                  displayName: PUTImport
                - id: Search
                  name: Search
                  displayName: Search
          policies:
            - id: SiteAdmin-policy
              name: SiteAdmin
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type: role
              config:
                roles: "[{\"id\":\"SiteAdmin\",\"required\":true}]"
            - id: user-policy
              name: user
              logic: POSITIVE
              decisionStrategy: UNANIMOUS
              type: client
              config:
                clients: "[\"computate.org\"]"
  instanceSelector:
    matchLabels:
      app: keycloak
