---
# Label: ansible_project_secret
# Title: create the Ansible secret for the project in OpenShift
# Mission: create the Ansible secret for the project in OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

apiVersion: v1
stringData:
  jdbcUrl: "jdbc:postgresql://postgres.{{POSTGRES_NAMESPACE}}.svc:5432/{{POSTGRES_DB_NAME}}"
  jdbcUsername: "{{POSTGRES_DB_USER}}"
  jdbcPassword: "{{POSTGRES_DB_PASSWORD}}"
  jdbcDatabase: "{{POSTGRES_DB_NAME}}"
  jdbcHost: "{{POSTGRES_HOST_NAME}}"
  jdbcPort: "{{POSTGRES_PORT}}"
  authRealm: "{{AUTH_REALM}}"
  authResource: "{{AUTH_RESOURCE}}"
  authSecret: "{{AUTH_SECRET}}"
  authUrl: "{{AUTH_URL}}"
  emailHost: "{{EMAIL_HOST_NAME}}"
  emailPort: "{{EMAIL_PORT}}"
  emailFrom: "{{EMAIL_FROM}}"
  emailSsl: "{{EMAIL_SSL}}"
  emailAuth: "{{EMAIL_AUTH}}"
  emailUsername: "{{EMAIL_USER}}"
  emailPassword: "{{EMAIL_PASSWORD}}"
  sslPassthrough: "{{ SSL_PASSTHROUGH | default(false) }}"
  sslKeystorePath: "{{SSL_KEYSTORE_PATH}}"
  sslJksPath: "{{SSL_JKS_PATH}}"
  sslAlias: "{{SSL_ALIAS}}"
  sslJksPassword: "{{SSL_JKS_PASSWORD}}"
kind: Secret
type: Opaque
